apiVersion: v1
appVersion: "1.0"
description: A Helm chart for creating a Carbyne Stack Castor tuple storage and management service.
name: castor
version: 0.1.0
keywords:
- carbynestack
- castor
home: https://carbynestack.io
sources:
- https://github.com/carbynestack/castor
maintainers:
- name: CarbyneStack.io
