spring:
  config:
    activate:
      on-profile: tuplestore-minio

carbynestack:
  castor:
    minio:
      endpoint: ${MINIO_ENDPOINT}
      bucket: minio-castor-bucket
      access-key: dummy-key
      secret-key: dummy-secret
