spring:
  profiles: cache-redis

carbynestack:
  castor:
    cache:
      reservation-store: "castor-reservation-store"
      consumption-store-prefix: "castor-consumption-"
      telemetry-interval: 5184000 #24h in seconds
      telemetry-ttl: 15552000 #72h in seconds
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
