apiVersion: v1
kind: Service
metadata:
  name: {{ include "castor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "castor.name" . }}
    helm.sh/chart: {{ include "castor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
{{ .Values.service.annotations | toYaml | trim | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 10100
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "castor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
